demo button
hatchways/team-oak pull request #51
Opened 2022-01-13 03:07 UTC by cl-codes

### What this PR does (required):
- added demo button to login and signup pages
- this is a login button with a hardcoded username and password
- 
### Screenshots 
![Screen Shot 2022-01-12 at 10 05 42 PM](https://user-images.githubusercontent.com/96796802/149258742-b795aa5a-fab1-422f-a372-aab3cfb4321a.png)
![Screen Shot 2022-01-12 at 10 06 23 PM](https://user-images.githubusercontent.com/96796802/149258755-c2401171-41ae-4836-8c23-7d3c7f24e35c.png)

2022-01-13 12:48 UTC, ezeilo-su reviewed
Nice job with this one :+1:

2022-01-14 00:56 UTC, moffatethan requested changes
One comment for you! Overall, great work on the button placement but would like to some changes. 

Thanks! Let me know if you have any questions

2022-01-14 00:56 UTC, moffatethan commented on client/src/pages/Login/DemoButton.tsx
> +  };
Not quite the approach I was thinking of. With the back-end work we should make a new method in the auth context to just hit the demo route (for now this can do nothing until the backend is implemented)

Therefore we don't need to worry about any credentials on the frontend.

2022-01-14 01:08 UTC, cl-codes commented on client/src/pages/Login/DemoButton.tsx
> +  };
got it - removed this section in latest version.

2022-01-14 23:25 UTC, moffatethan approved these changes
I'll approve, once the back-end is finished up we'll need to make some changes. Good work.

2022-01-15 00:14 UTC, merged