FE: Profile Details page
hatchways/team-oak pull request #56
Opened 2022-01-14 15:08 UTC by rizperdana

Fixes #20

### What this PR does (required):
- This MR will add profile detail skeleton

### Screenshots / Videos (front-end only):
![Screenshot 2022-01-14 220339](https://user-images.githubusercontent.com/11896928/149537601-196b597e-842b-4a6f-99a5-e34d7c169dfb.png)

### Any information needed to test this feature (required):
- `npm run start`
- login / register as user
- once you get in the dashboard, navigate your url to `/profile/detail`

### Any issues with the current functionality (optional):
- It's already responsive, but i need more input regarding this

2022-01-14 20:48 UTC, ezeilo-su reviewed
Good work with this one.

2022-01-15 01:58 UTC, moffatethan requested changes
Thanks for doing this, some comments on quality and quick changes. I noticed the colouring in the UI is not even the right colour compared to the overall app. Let's fix that. Also **please uninstall v4 of MUI and continue using v5.**

While you have a good initial responsiveness on the UI. It's not properly responsive, take a look at my screenshot on my laptop. It's very squished and looks like content is chopped off. On tablet this is happening too.

Mobile:
<img width="501" alt="Screen Shot 2022-01-14 at 5 42 54 PM" src="https://user-images.githubusercontent.com/38387163/149604601-5ae49cf5-ee44-4142-ba78-0b3fcbd38cb3.png">

Tablet:
<img width="993" alt="Screen Shot 2022-01-14 at 5 57 38 PM" src="https://user-images.githubusercontent.com/38387163/149604626-21b55650-2c01-4dac-ad43-da7f8581b83f.png">

2022-01-15 01:58 UTC, moffatethan commented on client/package.json
> +    "@material-ui/pickers": "^3.3.10",
You've installed v4 of Material UI, we're on v5 of Material UI. Please remove these packages.

2022-01-15 01:58 UTC, moffatethan commented on client/package.json
> +    "faker": "^5.5.3",
I don't even see this being used anywhere so remove?

2022-01-15 01:58 UTC, moffatethan commented on client/package.json
> +    "@types/faker": "^5.5.3",
Same with this one too 😄

2022-01-15 01:58 UTC, moffatethan commented on client/src/pages/ProfileDetail/BookingForm/BookingForm.tsx
> +});
Wonder if there's a way to make this a bit more intuitive? I'm going to think on this more, if you could think as well that would be excellent!

2022-01-15 01:58 UTC, moffatethan commented on client/src/pages/ProfileDetail/BookingForm/BookingForm.tsx
> +  const bookForm = useFormik({
Good job using Formik here, could we also add in form validation with Yup schemas? Formik has great support for Yup.

2022-01-15 01:58 UTC, moffatethan commented on client/src/pages/ProfileDetail/BookingForm/BookingForm.tsx
> +                start time
```suggestion
                Start time
```

2022-01-15 01:58 UTC, moffatethan commented on client/src/pages/ProfileDetail/BookingForm/BookingForm.tsx
> +                end time
```suggestion
                End time
```

2022-01-15 01:58 UTC, moffatethan commented on client/src/pages/ProfileDetail/BookingForm/BookingForm.tsx
> +          send request
```suggestion
          Send Request
```

2022-01-15 01:58 UTC, moffatethan commented on client/src/pages/ProfileDetail/BookingForm/BookingForm.tsx
> +import { Box, Typography, Select, MenuItem, OutlinedInput, Grid, Button, Card } from '@material-ui/core';
You aren't using the right material UI version here, so please update this to MUI v5.

2022-01-15 01:58 UTC, moffatethan commented on client/src/pages/ProfileDetail/ProfileDetail.tsx
> +              <Box marginTop="20px" display="flex">
For MUI v5, let's use `sx` for this.

2022-01-15 01:58 UTC, moffatethan commented on client/src/pages/ProfileDetail/ProfileDetail.tsx
> +        <Box margin="0 auto" display="grid">
For MUI v5, let's use `sx` for these properties.

2022-01-15 01:58 UTC, moffatethan commented on client/src/pages/ProfileDetail/ProfileDetail.tsx
> +              <Box marginTop="10px" width="100%" textAlign="left" marginBottom="30px">
As mentioned before, MUI v5 has `sx` so let's use that for these properties.

2022-01-19 12:34 UTC, rizperdana commented
Hi @moffatethan i made some revision for this 
![image](https://user-images.githubusercontent.com/11896928/150129926-82abb587-1a6b-4486-999c-7eaf56c85133.png)

also revamping those responsive element
![image](https://user-images.githubusercontent.com/11896928/150130070-77c6fdda-1c0f-4016-95ba-1d92a152b2bd.png)

additionally i fix those weird date time picker function i made last time by using simplified version of native datepicker
![image](https://user-images.githubusercontent.com/11896928/150130434-86426aac-0d55-4076-a082-84360d7a92ca.png)


TODO: i havent done fixing those form validation you suggesting, i will looking forward to it after i fixed my faulty hard drive here

2022-01-20 15:35 UTC, closed without merging