IN/FE: Full integration of Notifications
hatchways/team-oak pull request #94
Opened 2022-01-29 22:40 UTC by Habib-Ahmad

### What this PR does (required):
-This PR uses socket.io to listen for incoming notifications and alert the user.
-All unread notifications can be accessed from the notifications button.
-When the notification drop down is opened, messages are marked as read.
-Clicking a notification takes the user to the appropriate route (i.e bookings page for bookings notifications, messages for user notifications)
-Closes #10 

### Screenshots / Videos (front-end only):
![image](https://user-images.githubusercontent.com/61251497/151679808-9135c337-284e-4d54-b896-cdaab27af3d1.png)

### Any information needed to test this feature (required):
- The backend APIs, which have not been merged yet are required.

2022-01-31 22:00 UTC, ezeilo-su commented
Hey @Habib-Ahmad, please confirm that you're using the appropriate base branch for this PR

2022-02-01 10:26 UTC, Habib-Ahmad commented
> Hey @Habib-Ahmad, please confirm that you're using the appropriate base branch for this PR

This branch was created from main. Did you notice something wrong?

2022-02-01 18:48 UTC, moffatethan requested changes
Can we see the UI of the notifications instead of just the circle?

2022-02-01 18:48 UTC, moffatethan commented on client/src/components/Navbar/Notification/Notifications.tsx
> +  const route = notif.type === 'booking' ? '/bookings' : notif.type === 'user' ? '/messages' : {};
A bit odd approach, ideally this data is attached on the notification itself but for times sake, this is fine for now.

2022-02-03 04:23 UTC, moffatethan approved these changes

2022-02-03 13:14 UTC, merged